export const CHECK_AUTH = 'checkAuth'
export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const REGISTER = 'register'
export const ADD_WALLET = 'addWallet'
export const FETCH_WALLETS = 'fetchWallet'
export const FAST_BUY_TRANSACTION = 'fastBuyTransaction'
export const FAST_SELL_TRANSACTION = 'fastSellTransaction'
