export const PURGE_AUTH = 'logOut'
export const SET_AUTH = 'setUser'
export const SET_WALLETS = 'setWallets'
export const SET_MARKET_HISTORIES_BUY = 'setMarketHistoriesBuy'
export const SET_MARKET_HISTORIES_SELL = 'setMarketHistoriesSell'
